export const MAIN_ROUTE = "/"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const BLOG_ROUTE = "/blog"
export const FORUM_ROUTE = "/forum"
export const HELP_ROUTE = "/help"